### ISSUE TITLE
New version needed

### ISSUE THREAD

**Issue by mhalano** [nhandler/packer-snap#1]
Hi Nathan,

A guy called Andre Bacao released a most updated Packer snap: https://uappexplorer.com/app/packer-abacao.abacao. The idea is, if you don't mind, give up of this snap name so he could use the "packer" name for snap, so just one Snap, the most updated, will be called "packer".

**Comment by nhandler** [comment]
I have updated the snap to 1.0.0 and uploaded it to the stable channel. I have also setup automatic builds and uploads to the edge channel that will track the latest commits to packer in git.
